services:
  - type: web
    name: farm-tech-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://farm-tech-backend.onrender.com
